---
title: "OddsFinder"
output: pdf_document
date: "2024-02-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r SCORESANDSODDS}
profit <- list()
for (link in links) {
  theurl <- link
  
  file<-read_html(theurl)
  date <- html_node(file,css='.reverse span:nth-child(5)')
  date_string <- html_text(date)
  parsed_date <- strptime(date_string, format = "%a %m/%d %I:%M%p")
  formatted_date <- format(parsed_date, "%Y-%m-%d")
  if (formatted_date != Sys.Date() ){
    next
  }
  tables<-html_nodes(file, "table")
  table1 <- html_table(tables[1], header = TRUE)
  table1[[1]][4]
  
  table2 <- html_table(tables[2], fill = TRUE)
  table2
  player_name <- html_text(html_node(file, css = ".page-footer .hydrated , h4"))
  print(player_name)
  
  newtable <- data.frame(table1)
  reretable <- newtable[-c(1:3, 5:11)]
  reretable <- data.frame(reretable[-c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22), ])
  colnames(reretable) <- "Prizepicks"
  reretable$Prizepicks <- str_remove(reretable$Prizepicks, " MORE +")
  reretable$Prizepicks <- str_remove(reretable$Prizepicks, " \\+")
  
  
  finalrownames <- c("Points", "Rebounds", "Assists", "Blocks", "Steals", "3 Pointers", "Points & Rebounds", "Points & Assists", "Points, Rebounds, & Assists", "Rebounds & Assists", "Turnovers")
  if (nrow(data.frame(table2)) == 0) {
    next
  }
  if (nrow(reretable) == 0) {
    next
  }
  reretable <- replace(reretable, is.na(reretable), FALSE)
  final <- data.frame(table2)
  final <- final[-c(1)]
  final <- cbind (reretable, final)
  final

  for (i in seq_len(nrow(final))) {
    if (final$Prizepicks[i] == final$Line[i]) {
      if (final$Over[i] <= -130) {
        profit[[length(profit) + 1]] <- list(
        Player = player_name,
        RowName = finalrownames[i],
        Line = final$Prizepicks[i],
        Over_Under = "Over",
        Odds = final$Over[i])
      }
    
    if (final$Under[i] <= -130) {
      profit[[length(profit) + 1]] <- list(
        Player = player_name,
        RowName = finalrownames[i],
        Line = final$Prizepicks[i],
        Over_Under = "Under",
        Odds = final$Under[i])
      }
    }
  }
  print(profit)
  
  player_name <- sub(".*/([^/]+)$", "\\1", theurl)


  print(player_name)
  print(profit)
}
profit <- bind_rows(lapply(profit, as.data.frame))
profit
```



```{r}

library(httr)
library(jsonlite)

prizepicks_url <- "https://partner-api.prizepicks.com/projections?league_id=7&per_page=10"

get_prizepicks_lines <- function(url) {
  data <- fromJSON(url)
  return(data)
}

#If 403 error, copy data from website and save to a local .json file:
#prizepicks <- fromJSON("~/Desktop/prizepicks.json")
prizepicks <- get_prizepicks_lines(prizepicks_url)

prizepicks_1 <- data.frame(prizepicks[[1]])
prizepicks_2 <- data.frame(prizepicks[[2]])


#remove demons and goblins
prizepicks_1 <- prizepicks_1[prizepicks_1$attributes$odds_type == "standard", ] 


#get necessary columns
prizepicks_1 <- data.frame(cbind(prizepicks_1$attributes$description, prizepicks_1$attributes$line_score, 
prizepicks_1$attributes$stat_type, prizepicks_1$attributes$start_time, 
  prizepicks_1$relationships$league$data$id, 
prizepicks_1$relationships$new_player$data$id, 
prizepicks_1$relationships$stat_type$data$id))


colnames(prizepicks_1) <- c("participant_name", "handicap", "sportsbooks.bookie_key", "start_time", "league_id", "player_id", "market_id")


#update prizepicks 1 names based on player id from prizepicks 2
for (j in 1:length(prizepicks_2$id)) {
  for (i in 1:length(prizepicks_1$player_id)) {
    if (prizepicks_2$id[j] == prizepicks_1$player_id[i]) {
      prizepicks_1$participant_name[i] <- prizepicks_2$attributes$display_name[j]
    }
  }
}
#add league
league_id_and_league <- na.omit(data.frame(unique(prizepicks_2$attributes$league_id), unique(prizepicks_2$attributes$league)))
colnames(league_id_and_league) <- c("id", "league")

for (j in 1:nrow(league_id_and_league)) {
  for (i in 1:nrow(prizepicks_1)) {
    if (league_id_and_league$id[j] == prizepicks_1$league_id[i]) {
      prizepicks_1$league[i] <- league_id_and_league$league[j]
    }
  }
}

prizepicks_nba <- prizepicks_1[prizepicks_1$league == "NBA", ]
prizepicks_nba$sportsbooks.bookie_key <- ifelse(prizepicks_nba$sportsbooks.bookie_key == "Pts+Rebs", "Points & Rebounds", prizepicks_nba$sportsbooks.bookie_key)
prizepicks_nba$sportsbooks.bookie_key <- ifelse(prizepicks_nba$sportsbooks.bookie_key == "Pts+Asts", "Points & Assists", prizepicks_nba$sportsbooks.bookie_key)
prizepicks_nba$sportsbooks.bookie_key <- ifelse(prizepicks_nba$sportsbooks.bookie_key == "Pts+Rebs+Asts", "Points, Rebounds, & Assists", prizepicks_nba$sportsbooks.bookie_key)
prizepicks_nba$sportsbooks.bookie_key <- ifelse(prizepicks_nba$sportsbooks.bookie_key == "Rebs+Asts", "Rebounds & Assists", prizepicks_nba$sportsbooks.bookie_key)
prizepicks_nba$sportsbooks.bookie_key <- ifelse(prizepicks_nba$sportsbooks.bookie_key == "Blocked Shots", "Blocks", prizepicks_nba$sportsbooks.bookie_key)
prizepicks_nba$sportsbooks.bookie_key <- ifelse(prizepicks_nba$sportsbooks.bookie_key == "3-PT Made", "3 Pointers", prizepicks_nba$sportsbooks.bookie_key)

prizepicks_nba

```




```{r Final Output}
library(tools)
colnames(prizepicks_nba)[colnames(prizepicks_nba) == "participant_name"] <- "Player"

# Sample player names
profit                                           
prizepicks_nba

# Remove dashes and capitalize player names
profit$Player <- gsub("-", " ", profit$Player)
profit$Player <- toupper(profit$Player)
prizepicks_nba$Player <- gsub("-", " ", prizepicks_nba$Player)
prizepicks_nba$Player <- toupper(prizepicks_nba$Player)
matched_rows <- data.frame(Player = character(), RowName = character(), Line = character())


# Iterate over each row in profit
for (i in seq_len(nrow(profit))) {
  # Check if Player and sportsbooks.bookie_key are not NA
  if (!is.na(profit$Player[i]) & !is.na(profit$RowName[i])) {
    # Check if there is a matching row in prizepicks_nba for the current player and attribute
    if (any(prizepicks_nba$Player == profit$Player[i] & prizepicks_nba$sportsbooks.bookie_key == profit$RowName[i]& prizepicks_nba$handicap == profit$Line[i])) {
      matched_rows <- rbind(matched_rows, profit[i, ])
    }
  }
}

# Update profit with matched rows
profit2 <- matched_rows

print(profit2[order(profit2$Odds, decreasing = FALSE), ]   )

log_parlay(profit2)
parlays_df

write.csv(parlays_df, file = "parlays.csv")


```







```{r}
check_result <- function(player_name, Category, line, over_under) {
  
newurl <- getWebsite(player_name)

if (player_name == "TIM HARDAWAY JR."){
  newurl <- "https://www.scoresandodds.com/prop-bets/16879/tim-hardaway"
}
if (player_name == "TYRESE MAXEY"){
  newurl <- "https://www.scoresandodds.com/prop-bets/2439150/tyrese-maxey"
}
if (player_name == "Michael Porter Jr."){
  newurl <- "https://www.scoresandodds.com/prop-bets/409154/michael-porter"
}
if (Category == "Threes"){
  Category <- "3 Pointers"
}
if (Category == "Points, Rebounds, Assists"){
  Category <- "Points, Rebounds, & Assists"
}
file<-read_html(newurl)
tables<-html_nodes(file, "table")
table2 <- html_table(tables[2], fill = TRUE)
table2 <- data.frame(table2)
actual_value <- as.numeric(table2$Actual[table2$Consensus == Category])
if (is.na(all(table2$Actual == 0))){
    return (-1)
}
if (all(table2$Actual == 0)){
    return (-1)
}

if (is.na(actual_value)){
    actual_value=0
}
line <- as.numeric(line)
if (over_under == "Over") {
    if (actual_value > line) {
      return(1)
    } else {
      return(0)
    }
  } else {
    if (actual_value < line) {
      return(1)
    } else {
      return(0)
    }
  }
}  



parlay_checker <- function(parlay){
    result <- 0
    for (i in 1:nrow(parlay)){
      if (check_result(parlay[i,1],parlay[i,2],parlay[i,3],parlay[i,4])==-1) {
        next
      }
      
      result <- check_result(parlay[i,1],parlay[i,2],parlay[i,3],parlay[i,4]) + result
    
    }
    return(result)
}




result_for_players <- function(date_given) {
  parlay_number <- subset(parlays_df, Date == date_given)[1,6]
  index <- ((parlay_number-1)*5) + 1
  for (i in index:nrow(parlays_df)) {
  
  
    parlays_df$Player
    result <- check_result(parlays_df[i,1], parlays_df[i,2], parlays_df[i,3], parlays_df[i,4])
    parlays_df$Player_Result[i] <- result
  }
}

result_for_parlays <- function(date_given) {
  parlay_number <- subset(parlays_df, Date == date_given)[1,6]
  for (i in parlay_number:parlays_df[nrow(parlays_df),6]) {
  
    print(i)
    result <- parlay_checker(subset(parlays_df, ParlayID == i))
    parlays_df$Parlay_Result[parlays_df$ParlayID == i] <<- result
  }
}

has_minus_one <- function(parlay_id) {
  player_results <- parlays_df$Player_Result[parlays_df$ParlayID == parlay_id]
  if (-1 %in% player_results) {
    return(TRUE)
  } else {
    return(FALSE)
  }
}
```





```{r For finding result of every player}
parlay_number <- subset(parlays_df, Date == Sys.Date())[1,6]
  index <- ((parlay_number-1)*5) + 1
for (i in index:nrow(parlays_df)) {
  
    print(parlays_df[i,]$Player)
    result <- check_result(parlays_df[i,1], parlays_df[i,2], parlays_df[i,3], parlays_df[i,4])
    print(result)
    parlays_df$Player_Result[i] <- result
}


```




```{r For result of every parlay}
parlay_number <- subset(parlays_df, Date == Sys.Date())[1,6]
  for (i in parlay_number:parlays_df[nrow(parlays_df),6]) {
  
    print(i)
    result <- parlay_checker(subset(parlays_df, ParlayID == i))
    parlays_df$Parlay_Result[parlays_df$ParlayID == i] <- result
  }
```





```{r For Calculating Returns}
parlays_df[nrow(parlays_df),6]
x<- 5
calculate_roi <- function(parlays_df) {
  ROI <- 0
  bank_counter <- 0
  for (i in 1:parlays_df[nrow(parlays_df),6]){
    print(parlays_df$Parlay_Result[parlays_df$ParlayID == i][1])
    parlays_results <- parlays_df$Parlay_Result[parlays_df$ParlayID == i][1]
    if (has_minus_one(i) & parlays_results== 4){
      ROI <- (ROI + 5*x )
      bank_counter <- bank_counter +5
    }else if (has_minus_one(i) & parlays_results == 3) {
      print(bank_counter)
      ROI <- (ROI + 1.5*x)
      bank_counter <- bank_counter +5
      print(bank_counter)
    }else if (has_minus_one(i) & parlays_results <3){
      bank_counter<- bank_counter+5
    }
    if ( !has_minus_one(i) & parlays_results == 5) {
      ROI <- (ROI + 10*x )
      bank_counter <- bank_counter +5
    } else if (!has_minus_one(i) & parlays_results == 4) {
      print(bank_counter)
      ROI <- (ROI + 2*x)
      bank_counter <- bank_counter +5
      print(bank_counter)
    } else if (!has_minus_one(i) & parlays_results == 3) {
      ROI <- (ROI +0.4*x)
      bank_counter <- bank_counter +5
    } else if (!has_minus_one(i)){
      ROI <- ROI 
      bank_counter <- bank_counter +5
    }
  }
  print(ROI)
  ROI <- (ROI-bank_counter)/bank_counter
  print(bank_counter)
  

  return(ROI)
 
} 
calculate_roi(parlays_df)

```





```{r LOG Function}
log_parlay <- function(df) {
  count <<- parlays_df[nrow(parlays_df),6] + 1
  if (nrow(df) >= 5) {
    df <- df[order(df$Odds, decreasing = FALSE), ]
    df_unique <- distinct(df, Player, .keep_all = TRUE)  # Remove duplicate player names
    df_unique <- na.omit(df_unique)
    df_unique <- filter_non_existing_rows(parlays_df, df_unique)
    parlay_props <- df_unique[order(df_unique$Odds, decreasing = FALSE), ][1:5, ]
    parlay_props <- na.omit(parlay_props)
    new_row <- data.frame(Player = parlay_props$Player,
                          RowName = parlay_props$RowName,
                          Line = parlay_props$Line,
                          Over_Under = parlay_props$Over_Under,
                          Odds = parlay_props$Odds,
                          ParlayID = rep(count, nrow(parlay_props)), 
                          Date = rep(as.character(Sys.Date()), nrow(parlay_props)), stringsAsFactors = FALSE, Player_Result = 0, Parlay_Result = 0)
    if (nrow(new_row) >= 5) {
      parlays_df <<- rbind(parlays_df, new_row)
    }
    return(new_row)
  } else {
    return(NULL)
  }
}

library(dplyr)
filter_non_existing_rows <- function(df1, df2) {
  i <- 1
  while (i <= nrow(df2)) {
    if (nrow(filter(df1, Player == df2[i, 1], RowName == df2[i, 2], Line == df2[i, 3], Over_Under == df2[i, 4], Date == df2[i, 6])) > 0) {
      df2 <- df2[-i, ]
    } else {
      i <- i + 1
    }
  }
  return(df2)
}
profit2
filter_non_existing_rows(profit2, profit2[1,])
```