---
title: "ParlayMaker"
output: pdf_document
date: "2024-02-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r}
sortedprofit <- profit[order(profit$Odds, decreasing = FALSE), ]

twopick <- slice_min(profit2, profit2$Odds, n = 2)

threepick <- slice_min(profit2, profit2$Odds, n = 3)

fourpick <- slice_min(profit2, profit2$Odds, n = 4)

fivepick <- slice_min(profit2, profit2$Odds, n = 5)

sixpick <- slice_min(profit2, profit2$Odds, n = 6)

twopick
threepick
fourpick
fivepick
sixpick
```

```{r}
twoman <- function(money, correct) {
  if (correct < 2) {
    return (0 * money)
  }
  else {
    return (3 * money)
  }
}

threemanpower <- function(money, correct) {
  if (correct < 3) {
    return (0 * money)
  }
  else {
    return (5 * money)
  }
}

threemanflex <- function(money, correct) {
  if (correct < 2) {
    return (0 * money)
  }
  if (correct == 2) {
    return (1.25 * money)
  }
  else {
    return (2.25 * money)
  }
}

fourmanpower <- function(money, correct) {
  if (correct < 4) {
    return (0 * money)
  }
  else {
    return (10 * money)
  }
}

fourmanflex <- function(money, correct) {
  if (correct < 3) {
    return (0 * money)
  }
  if (correct == 3) {
    return (1.5 * money)
  }
  else {
    return (5 * money)
  }
}

fiveman <- function(money, correct) {
  if (correct < 3) {
    return (0 * money)
  }
  if (correct == 3) {
    return (0.4 * money)
  }
  if (correct == 4) {
    return (2 * money)
  }
  else {
    return (10 * money)
  }
}

sixman <- function(money, correct) {
  if (correct < 4) {
    return (0 * money)
  }
  if (correct == 4) {
    return (0.4 * money)
  }
  if (correct == 5) {
    return (2 * money)
  }
  else {
    return (25 * money)
  }
}
```

```{r}
check_result <- function(player_name, Category, line, over_under) {
newurl <- getWebsite(player_name)
file<-read_html(newurl)
tables<-html_nodes(file, "table")
table2 <- html_table(tables[2], fill = TRUE)
table2 <- data.frame(table2)
actual_value <- table2$Actual[table2$Consensus == Category]
if (over_under == "Over") {
    if (actual_value > line) {
      return(1)
    } else {
      return(0)
    }
  } else {
    if (actual_value < line) {
      return(1)
    } else {
      return(0)
    }
  }
}
```

```{r}
score <- 0
for (i in c(1:2)) {
  result <- check_result(twopick$Player[i], twopick$RowName[i], as.numeric(twopick$Line[i]), twopick$Over_Under[i])
  score <- score + result
}
twoman(1, score)
```

```{r}
score <- 0
for (i in c(1:3)) {
  result <- check_result(threepick$Player[i], threepick$RowName[i], as.numeric(threepick$Line[i]), threepick$Over_Under[i])
  score <- score + result
}
threemanflex(1, score)
threemanpower(1, score)
```

```{r}
score <- 0
for (i in c(1:4)) {
  result <- check_result(fourpick$Player[i], fourpick$RowName[i], as.numeric(fourpick$Line[i]), fourpick$Over_Under[i])
  score <- score + result
}
fourmanflex(1, score)
fourmanpower(1, score)
```

```{r}
score <- 0
for (i in c(1:5)) {
  result <- check_result(fivepick$Player[i], fivepick$RowName[i], as.numeric(fivepick$Line[i]), fivepick$Over_Under[i])
  score <- score + result
}
fiveman(1, score)
```


```{r}
score <- 0
for (i in c(1:6)) {
  result <- check_result(sixpick$Player[i], sixpick$RowName[i], as.numeric(sixpick$Line[i]), sixpick$Over_Under[i])
  score <- score + result
}
sixman(1, score)
```

